### ISSUE TITLE
Search for Posts

### ISSUE THREAD

**Issue by JoeQuigley1** [JoeQuigley1/pp5-fe-bike-brothers#10]
As a user I can for posts title and user, so that I can find the posts and user profiles I am most interested in.

###  Acceptance Criteria

- [x] User can search the search bar to filter through posts 
- [x] Search bar displays filtered data 

### Tasks

- [x] Add Search Bar to relevant posts page
