### ISSUE TITLE
Delete Comment

### ISSUE THREAD

**Issue by JoeQuigley1** [JoeQuigley1/pp5-fe-bike-brothers#12]
As an owner of a comment I can delete my comment so that I can control removal of my comment from the application.

###  Acceptance Criteria

- [x] User can delete a comment in the comment form of a post
- [x] Comment data is removed from the BackEnd API
- [x] Comment is no longer displayed

### Tasks

- [x] Add delete comment icon
