### ISSUE TITLE
Contact Page

### ISSUE THREAD

**Issue by JoeQuigley1** [JoeQuigley1/pp5-fe-bike-brothers#13]
As a User I can Contact the site admin  of the site through a contact Form

### Acceptance Criteria

- [x] A contact page is accesible from the navbar. 
- [x] Contact Form submits information which is sent to the BackEnd API
- [x] Contact Form data is accessible in BackEnd API

### Tasks

- [x] Create a Contact Form
- [x] Create a Contact PAge
- [x] Use a redirect so the user is sent to a confirmation page so they know their query has been received and they can continue.
