### ISSUE TITLE
Meet up Page

### ISSUE THREAD

**Issue by JoeQuigley1** [JoeQuigley1/pp5-fe-bike-brothers#14]
As a user I can view a bike Meet up so that I can see the details of  meetups  planned.

###  Acceptance Criteria

- [x] Logged in user can navigate to Meetups Page  from an icon link in the Navbar

- [x] Meetups are displayed on the page

- [x] Meetup title is clickable 

### Tasks

- [x] Create a Meetup page

**Comment by JoeQuigley1** [comment]
Preview
