### ISSUE TITLE
Edit Profile

### ISSUE THREAD

**Issue by JoeQuigley1** [JoeQuigley1/pp5-fe-bike-brothers#17]
As a user I can edit my profile so that I can update or change my information.

### Acceptance Criteria

- [x] Dropdown is available and allows user to edit profile info
- [x] Edit forms allows the user to change the username, password and edit the profile details

### Tasks

- [x] Create a Username Form
- [x] Create a Password Form
- [x] Create a Profile Edit Form
