### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by JoeQuigley1** [JoeQuigley1/pp5-fe-bike-brothers#18]
As a user you can view a navbar from every page so that I can navigate easily betwen pages

###  Acceptance Criteria

- [x] Navbar is displayed on all pages

- [x] Navbar displays different icons depending on the users authentification status  

- [x]  Icons are clickable and lead to the desired page
- [x] Hamburger is present in smaller screen sizes  

### Tasks

- [x] Create Navbar
- [x] Create links and icons
- [x] Confirm Hamburger is functional is smaller screen sizes
