### ISSUE TITLE
Sign In

### ISSUE THREAD

**Issue by JoeQuigley1** [JoeQuigley1/pp5-fe-bike-brothers#19]
As a user I can Sign in to the app so that I can gain access to all features available for a signed in user.

### Acceptance Criteria

- [x] Link to Sign in Page in Navbar

- [x] Signed in users are redirected to the homepage

- [x] All functionality for Signed in users are available

### Tasks

- [x] Create Sign in form

- [x] Add link to Navbar
