### ISSUE TITLE
Post

### ISSUE THREAD

**Issue by JoeQuigley1** [JoeQuigley1/pp5-fe-bike-brothers#2]
As a user I can view the posts page so that I can see the details of the post.

###  Acceptance Criteria

- [x] User can click on a post to view the information associated with that posts
- [x] Users can read  and write comments and like the post

### Tasks

- [x] Create post detail page
- [x] Add a comment form to the post
