### ISSUE TITLE
Sign Up 

### ISSUE THREAD

**Issue by JoeQuigley1** [JoeQuigley1/pp5-fe-bike-brothers#20]
As a user I can sign up and register as a user so that I can gain access to the site

### Acceptance Criteria

- [x] Sign up must be accesible from the navbar

- [x] Users are redirected to the login page on successful sign up

- [x] A user is created in the BackEnd API

### Tasks

- [x] Create a sign up form

- [x] Add a clickable  link to Nabar to redirect user

- [x] Confirm data is sent to the  API
