### ISSUE TITLE
Create Comment (Posts)

### ISSUE THREAD

**Issue by JoeQuigley1** [JoeQuigley1/pp5-fe-bike-brothers#26]
As a logged in user I can add comments to a post so that I can share my thoughts about the post

###  Acceptance Criteria

- [x] User can create a comment in the comment form of a post
- [x] Comment data is sent to the BackEnd API
- [x] Comments are displayed after they are submitted

### Tasks

- [x] Create a comment form
