### ISSUE TITLE
Edit Comment

### ISSUE THREAD

**Issue by JoeQuigley1** [JoeQuigley1/pp5-fe-bike-brothers#27]
As an owner of a comment I can edit comments on a post which I have made so that I can correct any mistakes

###  Acceptance Criteria

- [x] User can edit a comment in the comment form of a post
- [x] Comment data is sent to the BackEnd API
- [x] Comments are displayed after they are submitted

### Tasks

- [x] Create a comment form
