### ISSUE TITLE
View Comments

### ISSUE THREAD

**Issue by JoeQuigley1** [JoeQuigley1/pp5-fe-bike-brothers#28]
As a user I would like to read comments made by other users so that I can connect with the community

###  Acceptance Criteria

- [x] Comments are visible under the post
- [x] Number of comments is displayed beside the comment icon

### Tasks

- [x] Add comment form to post
- [x] Add Comment icon to post
