### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by JoeQuigley1** [JoeQuigley1/pp5-fe-bike-brothers#32]
As a user I can navigate to an about page so that I can get more information about the site

###  Acceptance Criteria

- [x] Accessible from Navbar
- [x] About page renders successsfully and displays information about the app.

### Tasks

- [x] Create an About page with information about the app.
- [x] Add a clickable link in the navbar which allows users to navigate to the page.
