### ISSUE TITLE
Delete Meetup

### ISSUE THREAD

**Issue by JoeQuigley1** [JoeQuigley1/pp5-fe-bike-brothers#35]
As an owner of a meetup I can choose to delete a Meetup so that if an event is no longer taking  place it is removed form the application

###  Acceptance Criteria

- [x] User can click into their own Meetup and using the three dots menu delete their meetup

- [x] Data is deleted from the BackEnd API

- [x] Meetup is no longer visible on the Meetup page

### Tasks

- [x] Add delete button to three dots menu
