### ISSUE TITLE
Like/Unlike Posts

### ISSUE THREAD

**Issue by JoeQuigley1** [JoeQuigley1/pp5-fe-bike-brothers#4]
As a user I can like and unlike a post so that I can show my support for the posts that interest me

###  Acceptance Criteria

- [x] User can like posts by clicking the like icon
- [x] Users can unlike posts by clicking the like icon
- [x] Data is sent to the BackEnd API

### Tasks
- [x] Add a like icon underneath the post detail
