### ISSUE TITLE
Confirmation Page

### ISSUE THREAD

**Issue by JoeQuigley1** [JoeQuigley1/pp5-fe-bike-brothers#40]
As a user I can contact the admin directly so that I can can ask question or give feedback.

###  Acceptance Criteria

- [x] Confirmation page is displayed once the user submits the Contact Form
- [x] Navbar is accesible from the Confirmation Page
- [x] Confirmation message is displayed

### Tasks
- [x] Create a Confirmation PAge
