### ISSUE TITLE
Feed Page

### ISSUE THREAD

**Issue by JoeQuigley1** [JoeQuigley1/pp5-fe-bike-brothers#41]
As a user I can navigate to the feed page so that I can see the posts of user I follow 

###  Acceptance Criteria

- [x] Feed page displays posts of users followed
- [x] Search bar is displayed and can filter through the posts

### Tasks

- [x] Add Feed Page
