### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by JoeQuigley1** [JoeQuigley1/pp5-fe-bike-brothers#43]
As a user I can navigate to the Home Page so that I can see all posts.

###  Acceptance Criteria

- [x] Home page displays all posts 
- [x] Search bar can filter post data by user and title

### Tasks

- [x] Add Home Page
