### ISSUE TITLE
User Profile

### ISSUE THREAD

**Issue by JoeQuigley1** [JoeQuigley1/pp5-fe-bike-brothers#6]
As a user I can view information about a specific user: username, name, bio, number of posts,  posts,  number offollows and users followed so that I can learn more about them

### Acceptance Criteria

- [x] Profile details are displyed
- [x] Number of likes and posts are displayed

### Tasks

- [x] Display relevant data to the profile
