### ISSUE TITLE
Follow/unfollow

### ISSUE THREAD

**Issue by JoeQuigley1** [JoeQuigley1/pp5-fe-bike-brothers#8]
As a user I can follow and unfollow other users so that I can see their content on the feed page

###  Acceptance Criteria

- [x] Followers are displayed on the relevant pages
- [x] Follow and Unfollow button appears by the username 
- [x] Follower data is sent to the BE API

### Tasks

- [x] Add follow buttons to relevant pages
